version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn pill.wsgi:application --bind 0.0.0.0:8980
    volumes: 
      - .:/project
    ports:
      - "8980:8980"

  nginx:
    container_name: nginx
    build: ./nginx
    image: pill/nginx
    ports:
      - "8988:8988"
    volumes:
      - .:/project
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  app-tier:
    driver: bridge

